<#
.SYNOPSIS
    Start / stop / check the keep-awake worker (sleep + lock-screen protection).

.DESCRIPTION
    Effective settings are resolved in this order:
      1. explicit command-line arguments
      2. config.json (machine-adapted, generated by check-machine.ps1)
      3. built-in defaults (display on, anti-lock on via F15 every 240s)

    'start'  launches keep-awake.ps1 as a hidden background PowerShell process
             and records its PID in .keep-awake.pid.
    'stop'   kills that process (Windows then drops all power requests
             automatically) and removes the PID file.
    'status' reports whether the worker is running, plus the newest log line.

.EXAMPLE
    powershell -NoProfile -ExecutionPolicy Bypass -File manage.ps1 -Action start
    powershell ... -File manage.ps1 -Action start -Minutes 120
    powershell ... -File manage.ps1 -Action start -NoAntiLock
    powershell ... -File manage.ps1 -Action status
#>
param(
    [Parameter(Mandatory = $true)]
    [ValidateSet('start', 'stop', 'status', 'restart')]
    [string]$Action,

    [double]$Minutes = 0,
    [switch]$AllowDisplayOff,
    [switch]$NoAntiLock,
    [int]$AntiLockIntervalSec = 0,
    [string]$AntiLockMethod = '',
    [int]$IntervalSeconds = 60
)

$dir     = Split-Path -Parent $MyInvocation.MyCommand.Path
$pidFile = Join-Path $dir '.keep-awake.pid'
$worker  = Join-Path $dir 'keep-awake.ps1'
$logFile = Join-Path $dir 'keep-awake.log'

# --- machine-adapted defaults -------------------------------------------------
$cfg = $null
if (Test-Path (Join-Path $dir 'config.json')) {
    try { $cfg = Get-Content (Join-Path $dir 'config.json') -Raw | ConvertFrom-Json } catch {}
}

$effAllowDisplayOff = $false
if ($PSBoundParameters.ContainsKey('AllowDisplayOff')) { $effAllowDisplayOff = [bool]$AllowDisplayOff }
elseif ($cfg -and $null -ne $cfg.keepDisplayOn)        { $effAllowDisplayOff = (-not [bool]$cfg.keepDisplayOn) }

$effNoAntiLock = $false
if ($PSBoundParameters.ContainsKey('NoAntiLock')) { $effNoAntiLock = [bool]$NoAntiLock }
elseif ($cfg -and $null -ne $cfg.antiLock)        { $effNoAntiLock = (-not [bool]$cfg.antiLock) }

$effAntiLockInterval = $AntiLockIntervalSec
if ($effAntiLockInterval -le 0) {
    if ($cfg -and $cfg.antiLockIntervalSec) { $effAntiLockInterval = [int]$cfg.antiLockIntervalSec }
    else { $effAntiLockInterval = 240 }
}

$effMethod = if ($AntiLockMethod) { $AntiLockMethod }
             elseif ($cfg -and $cfg.antiLockMethod) { [string]$cfg.antiLockMethod }
             else { 'key' }

# --- helpers --------------------------------------------------------------------
function Get-RunnerState {
    if (-not (Test-Path $pidFile)) { return @{ Alive = $false } }
    $storedPid = Get-Content $pidFile -ErrorAction SilentlyContinue | Select-Object -First 1
    if ("$storedPid" -notmatch '^\d+$') { return @{ Alive = $false; Stale = $true } }

    $proc = Get-Process -Id ([int]$storedPid) -ErrorAction SilentlyContinue
    # Verify the identity belongs to a powershell process so a recycled PID is not
    # mistaken for our worker.
    if ($proc -and $proc.ProcessName -match '^powershell') {
        return @{ Alive = $true; Id = $proc.Id; StartTime = $proc.StartTime }
    }
    return @{ Alive = $false; Stale = $true; StoredPid = $storedPid }
}

function Show-LastLogLine {
    $last = Get-Content $logFile -Tail 1 -ErrorAction SilentlyContinue
    if ($last) { Write-Host "[keep-awake] last log: $last" }
}

switch ($Action) {

    'start' {
        $state = Get-RunnerState
        if ($state.Alive) {
            Write-Host "[keep-awake] already running (pid $($state.Id)). Nothing to do."
            exit 0
        }
        Remove-Item $pidFile -ErrorAction SilentlyContinue

        $arguments = "-NoProfile -ExecutionPolicy Bypass -File `"$worker`" " +
                     "-IntervalSeconds $IntervalSeconds " +
                     "-AntiLockIntervalSec $effAntiLockInterval " +
                     "-AntiLockMethod $effMethod"
        if ($Minutes -gt 0)         { $arguments += " -Minutes $Minutes" }
        if ($effAllowDisplayOff)    { $arguments += ' -AllowDisplayOff' }
        if ($effNoAntiLock)         { $arguments += ' -NoAntiLock' }

        $proc = Start-Process powershell.exe -ArgumentList $arguments -WindowStyle Hidden -PassThru
        Set-Content -Path $pidFile -Value $proc.Id -Encoding ascii

        Start-Sleep -Milliseconds 1500
        if (Get-Process -Id $proc.Id -ErrorAction SilentlyContinue) {
            $disp = if ($effAllowDisplayOff) { 'system awake, display may sleep' } else { 'system + display awake' }
            $lock = if ($effNoAntiLock) { 'anti-lock off' } else { "anti-lock on ($effMethod / $($effAntiLockInterval)s)" }
            Write-Host "[keep-awake] started (pid $($proc.Id))."
            Write-Host "[keep-awake] mode: $disp; $lock"
            if ($Minutes -gt 0) { Write-Host "[keep-awake] auto-exits in $Minutes minute(s)." }
            Show-LastLogLine
        } else {
            Write-Warning '[keep-awake] worker exited immediately - last log lines:'
            Get-Content $logFile -Tail 5 -ErrorAction SilentlyContinue | Write-Host
            exit 1
        }
    }

    'stop' {
        $state = Get-RunnerState
        if ($state.Alive) {
            Stop-Process -Id $state.Id -Force
            Write-Host "[keep-awake] stopped (pid $($state.Id)). Normal power plan restored."
        } else {
            Write-Host '[keep-awake] not running.'
        }
        Remove-Item $pidFile -ErrorAction SilentlyContinue
        "$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')  STOPPED via manage.ps1" |
            Out-File $logFile -Append -Encoding utf8
    }

    'status' {
        $state = Get-RunnerState
        if ($state.Alive) {
            $since = ''
            if ($state.StartTime) { $since = ', up since ' + $state.StartTime.ToString('yyyy-MM-dd HH:mm:ss') }
            Write-Host "[keep-awake] RUNNING (pid $($state.Id)$since). Sleep and idle-lock are being prevented."
            Show-LastLogLine
            exit 0
        }
        Write-Host '[keep-awake] NOT running.'
        exit 1
    }

    'restart' {
        & (Join-Path $dir 'manage.ps1') -Action stop
        & (Join-Path $dir 'manage.ps1') -Action start -Minutes $Minutes `
            -AllowDisplayOff:$AllowDisplayOff -NoAntiLock:$NoAntiLock `
            -AntiLockIntervalSec $AntiLockIntervalSec -AntiLockMethod $AntiLockMethod `
            -IntervalSeconds $IntervalSeconds
    }
}
